import { slug } from './slug.js'

/**
 * Biblioteca curada de PDFs oficiales de currículum (MINEDUC, Currículum Nacional,
 * BCN, INDH, etc.) para 4° medio, por materia. NO incluye ensayos ni material de
 * la PAES — eso vive en paesLibrary.js, en su propia sección de la app.
 *
 * Se combina en tiempo de ejecución con los PDFs subidos por los propios
 * usuarios (backend.pdfs, en IndexedDB).
 *
 * Cada entrada: { title, topic, year, source, url }
 */
export const SEED_LIBRARY = {
  matematicas: [
    {
      title: 'Cuadernillo de Repaso: Eje Álgebra y Funciones',
      topic: 'Álgebra y funciones (ecuaciones, factorización, función lineal y cuadrática)',
      year: 2021,
      source: 'MINEDUC (Unidad de Currículum y Evaluación)',
      url: 'https://acceso.mineduc.cl/wp-content/uploads/2021/06/Cuadernillo-Matematica-eje-algebra-y-funciones-2021.pdf',
    },
    {
      title: 'Cuadernillo de Repaso: Eje Geometría',
      topic: 'Geometría (transformaciones, cuerpos geométricos, semejanza)',
      year: 2021,
      source: 'MINEDUC (Unidad de Currículum y Evaluación)',
      url: 'https://acceso.mineduc.cl/wp-content/uploads/2021/06/Cuadernillo-Matematica-eje-geometria.pdf',
    },
    {
      title: 'Cuadernillo de Repaso: Eje Números',
      topic: 'Números reales, potencias, raíces y logaritmos',
      year: 2021,
      source: 'MINEDUC (Unidad de Currículum y Evaluación)',
      url: 'https://acceso.mineduc.cl/wp-content/uploads/2021/06/Cuadernillo-Matematica-eje-numeros-2021.pdf',
    },
    {
      title: 'Cuadernillo de Repaso: Eje Probabilidad y Estadística',
      topic: 'Probabilidad y estadística descriptiva',
      year: 2021,
      source: 'MINEDUC (Unidad de Currículum y Evaluación)',
      url: 'https://acceso.mineduc.cl/wp-content/uploads/2021/06/Cuadernillo-Matematica-eje-probabilidad-y-estadistica.pdf',
    },
    {
      title: 'Programa Diferenciado: Límites, Derivadas e Integrales',
      topic: 'Cálculo introductorio (límites, derivadas e integrales)',
      year: 2021,
      source: 'MINEDUC / Biblioteca Digital MINEDUC',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14312/L%C3%ADmites%20Derivadas%20e%20Integrales%203%C2%B04%C2%B0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Programa Diferenciado: Probabilidades y Estadística Descriptiva e Inferencial',
      topic: 'Probabilidad y estadística inferencial',
      year: 2021,
      source: 'MINEDUC / Biblioteca Digital MINEDUC',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14318/Prob%20y%20Estadistica%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Programa Diferenciado: Geometría 3D',
      topic: 'Geometría en el espacio (cuerpos 3D, vistas, redes)',
      year: 2021,
      source: 'MINEDUC / Biblioteca Digital MINEDUC',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14317/Geometria%203D%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Programa de Estudio 4° Medio: Matemática (Formación General)',
      topic: 'Programa curricular completo de Matemática 4° medio',
      year: 2021,
      source: 'MINEDUC / Biblioteca Digital MINEDUC',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14340/Matematica%204%c2%b0M%20FG.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Texto del Estudiante Matemática 3°/4° Medio (SM) - Muestra',
      topic: 'Texto escolar oficial, fragmento de muestra (álgebra, funciones, geometría, probabilidad)',
      year: 2020,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/estudiante/621/articles-229921_textoescolar_muestra.pdf',
    },
    {
      title: 'Texto del Estudiante Matemática 3°/4° Medio (Santillana) - Muestra',
      topic: 'Texto escolar oficial, fragmento de muestra (álgebra, funciones, geometría, probabilidad)',
      year: 2020,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/sites/default/files/newtenberg/614/articles-145588_textoescolar_muestra.pdf',
    },
    {
      title: 'Matemática 4° Medio - Texto Adaptado (Macrotipo)',
      topic: 'Texto escolar completo adaptado, cobertura integral del currículum de 4° medio',
      year: 2025,
      source: 'MINEDUC (Educación Especial)',
      url: 'https://especial.mineduc.cl/wp-content/uploads/sites/31/2025/05/Matematica-4-Medio-Macro.pdf',
    },
    {
      title: 'Guía de Aprendizaje N°6: Estadística y Probabilidad',
      topic: 'Estadística y probabilidad (educación media personas jóvenes y adultas)',
      year: 2016,
      source: 'MINEDUC (EPJA)',
      url: 'https://epja.mineduc.cl/wp-content/uploads/sites/43/2016/04/GuiaN6MatematicaICiclodeEM.pdf',
    },
  ],
  lenguaje: [
    {
      title: 'Programa de Estudio 4° Medio: Lengua y Literatura',
      topic: 'Programa de estudio oficial completo (4 unidades) de Lengua y Literatura',
      year: 2021,
      source: 'MINEDUC – Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14330/Lengua%20y%20Literatura%204%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Programa de Estudio: Taller de Literatura (3° y 4° medio)',
      topic: 'Programa de la asignatura electiva Taller de Literatura',
      year: 2021,
      source: 'MINEDUC – Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14307/Taller%20Literatura%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Unidad 1: Lectura Dirigida de una Obra Clásica',
      topic: 'Comprensión y análisis literario (lectura literaria dirigida)',
      year: 2021,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/estudiante/621/articles-134937_recurso_pdf.pdf',
    },
    {
      title: 'Unidad 2: Interpretaciones de un Cuento',
      topic: 'Interpretación literaria y diálogo argumentativo',
      year: 2021,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/estudiante/621/articles-134943_recurso_pdf.pdf',
    },
    {
      title: 'Unidad 4: Crítica de Cine (Texto de Opinión)',
      topic: 'Géneros discursivos periodísticos: la crítica y el texto de opinión',
      year: 2021,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/estudiante/621/articles-134952_recurso_pdf.pdf',
    },
    {
      title: 'Unidad 4: Campaña de Propaganda',
      topic: 'Géneros discursivos persuasivos: la propaganda',
      year: 2021,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/estudiante/621/articles-134954_recurso_pdf.pdf',
    },
    {
      title: 'Planificación del Ensayo (Propuesta CNED)',
      topic: 'Ensayo (género discursivo): planificación y producción de un texto argumentativo',
      year: 2020,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/estudiante/621/articles-134948_recurso_pdf.pdf',
    },
    {
      title: 'Aprendo en Línea: Orientaciones de Trabajo (Clase 29)',
      topic: 'Producción oral y escrita: monólogo y carta personal',
      year: 2020,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/614/articles-179452_recurso_pdf.pdf',
    },
    {
      title: 'Taller de Literatura – Unidad 4: Poesía No Convencional',
      topic: 'Producción literaria: poesía experimental',
      year: 2021,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/estudiante/621/articles-135204_recurso_pdf.pdf',
    },
    {
      title: 'Nuevo Currículum 3° y 4° Medio: Lengua y Literatura',
      topic: 'Bases curriculares: principios, enfoques y objetivos de aprendizaje',
      year: 2019,
      source: 'Currículum Nacional / MINEDUC',
      url: 'https://www.curriculumnacional.cl/614/articles-133992_recurso_22.pdf',
    },
    {
      title: 'Bases Curriculares 3° y 4° Medio',
      topic: 'Marco curricular oficial de todas las asignaturas, incluye Lengua y Literatura',
      year: 2019,
      source: 'MINEDUC',
      url: 'https://www.curriculumnacional.cl/614/articles-91414_bases.pdf',
    },
  ],
  historia: [
    {
      title: 'Bases Curriculares 3° y 4° Medio: Historia y Educación Ciudadana',
      topic: 'Marco curricular oficial Historia, Geografía y Ciencias Sociales / Educación Ciudadana',
      year: 2019,
      source: 'Currículum Nacional (MINEDUC)',
      url: 'https://www.curriculumnacional.cl/sites/default/files/adjuntos/recursos/2026-04/articles-133992_recurso_21_0.pdf',
    },
    {
      title: 'Comprensión Histórica del Presente',
      topic: 'Historia de Chile siglo XX (Formación Diferenciada 3°/4° medio)',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14304/Comprens%20Historica%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Mundo Global',
      topic: 'Geografía y globalización (Formación Diferenciada 3°/4° medio)',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14347/Mundo%20Global%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Chile y la Región Latinoamericana',
      topic: 'Geografía y relaciones internacionales de Chile (Formación Diferenciada 3°/4° medio)',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14348/Chile%20y%20region%20latinoamericana.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Economía y Sociedad',
      topic: 'Sistema económico chileno (Formación Diferenciada 3°/4° medio)',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14306/Economia%20Sociedad%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Programa de Estudio Cuarto Año Medio: Historia, Geografía y Cs. Sociales',
      topic: 'Programa oficial de estudio Historia 4° medio',
      year: 2009,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/253/MONO-198.pdf?sequence=1&isAllowed=y',
    },
    {
      title: 'Formación Ciudadana',
      topic: 'Educación ciudadana y sistema político chileno',
      year: 2016,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/1929/mono-663.pdf?sequence=1&isAllowed=y',
    },
    {
      title: 'Orientaciones Curriculares para el Plan de Formación Ciudadana',
      topic: 'Formación ciudadana y participación democrática',
      year: 2016,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/467/MONO-391.pdf?sequence=1&isAllowed=y',
    },
    {
      title: 'Reforma Agraria Chilena: 50 años, historia y reflexiones',
      topic: 'Historia económica y social de Chile siglo XX',
      year: 2012,
      source: 'Biblioteca del Congreso Nacional (BCN)',
      url: 'https://obtienearchivo.bcn.cl/obtienearchivo?id=documentos/10221.1/69465/5/reforma_graria_chilena.pdf',
    },
    {
      title: 'Principales Reformas al Sistema Político 1990-2024',
      topic: 'Sistema político chileno post-dictadura',
      year: 2024,
      source: 'Biblioteca del Congreso Nacional (BCN)',
      url: 'https://obtienearchivo.bcn.cl/obtienearchivo?id=repositorio/10221/36152/1/BCNInforme_ReformasSistemaPolitico1990_2024.pdf',
    },
    {
      title: 'Derechos Humanos en el Aula',
      topic: 'Derechos humanos y educación',
      year: 2017,
      source: 'INDH (Instituto Nacional de Derechos Humanos)',
      url: 'https://www.indh.cl/bb/wp-content/uploads/2017/01/derechos-humanos-aula.pdf',
    },
    {
      title: 'Informe de Derechos Humanos para Estudiantes',
      topic: 'Derechos humanos para estudiantes de 7° básico a 4° medio',
      year: 2017,
      source: 'INDH (Instituto Nacional de Derechos Humanos)',
      url: 'https://www.indh.cl/wp-content/uploads/2017/01/informe-estudiantes-ddhh-segunda-edicion.pdf',
    },
    {
      title: '11 de Septiembre de 1973: Golpe de Estado',
      topic: 'Historia de Chile siglo XX: quiebre democrático de 1973',
      year: 2023,
      source: 'Memoria Chilena - Biblioteca Nacional de Chile',
      url: 'https://www.memoriachilena.gob.cl/archivos2/pdfs/MC0059400.pdf',
    },
  ],
  ciencias: [
    {
      title: 'Química: Programa de Estudio Cuarto Año Medio',
      topic: 'Equilibrio químico y química general',
      year: 2004,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/685/MONO-186.pdf?sequence=1&isAllowed=y',
    },
    {
      title: 'Biología: Célula, Genoma y Organismo',
      topic: 'Genética y evolución',
      year: 2004,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/293/MONO-235.pdf?sequence=1&isAllowed=y',
    },
    {
      title: 'Biología de los Ecosistemas (Formación Diferenciada)',
      topic: 'Ecología y sustentabilidad',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14310/Biol%20Ecosistemas%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Física: Formación Diferenciada en Ciencias',
      topic: 'Electromagnetismo y ondas',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14314/F%C3%ADsica%203%C2%B04%C2%B0M%20FD%20Ciencias.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Biología Celular y Molecular (Formación Diferenciada)',
      topic: 'Genética molecular',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14316/Biol%20Celular%20y%20Molecular%203%c2%b04%c2%b0M.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Química: Formación Diferenciada en Ciencias',
      topic: 'Química orgánica y equilibrio químico',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14315/Qu%C3%ADmica%203%C2%B04%C2%B0M%20FD%20Ciencias.pdf?sequence=4&isAllowed=y',
    },
    {
      title: 'Ciencias para la Ciudadanía 3° y 4° Medio (fragmento texto estudiante)',
      topic: 'Ciencia, tecnología y sociedad',
      year: 2020,
      source: 'MINEDUC - Biblioteca Digital',
      url: 'https://bibliotecadigital.mineduc.cl/bitstream/handle/20.500.12365/14767/prior_3M4M%20CsCiud.pdf?sequence=1&isAllowed=y',
    },
    {
      title: 'Programa de Estudio Química Formación Diferenciada 3° o 4° Medio',
      topic: 'Química orgánica y equilibrio químico',
      year: 2015,
      source: 'Currículum Nacional',
      url: 'https://www.curriculumnacional.cl/614/articles-133992_recurso_40.pdf',
    },
    {
      title: 'Biología 3° y 4° Medio - Texto del Estudiante',
      topic: 'Genética y evolución',
      year: 2014,
      source: 'Educrea (MINEDUC)',
      url: 'https://educrea.cl/wp-content/uploads/2015/04/Biologia_3y4_medio_2014-web.pdf',
    },
    {
      title: 'Física 3° y 4° Medio - Texto del Estudiante',
      topic: 'Electromagnetismo y ondas',
      year: 2014,
      source: 'Educrea (MINEDUC)',
      url: 'https://educrea.cl/wp-content/uploads/2015/04/Fisica_3y4_medio_2014-web.pdf',
    },
    {
      title: 'Química 3° y 4° Medio - Texto del Estudiante',
      topic: 'Química orgánica y equilibrio químico',
      year: 2014,
      source: 'Educrea (MINEDUC)',
      url: 'https://educrea.cl/wp-content/uploads/2015/04/Quimica_3y4_medio_2014-web.pdf',
    },
  ],
  ingles: [
    {
      title: 'Programa de Estudio: Inglés 4° Medio',
      topic: 'Currículum oficial e indicadores de progreso en inglés',
      year: 2021,
      source: 'MINEDUC / Currículum Nacional',
      url: 'https://www.curriculumnacional.cl/sites/default/files/adjuntos/recursos/2024-12/articles-140131_programa.pdf',
    },
    {
      title: 'SIMCE Inglés 2014 - Reading Sample Test 1',
      topic: 'Reading comprehension',
      year: 2014,
      source: 'Agencia de Calidad de la Educación',
      url: 'https://archivos.agenciaeducacion.cl/Simce_Reading_Sample_Test1-1.pdf',
    },
    {
      title: 'SIMCE Inglés 2014 - Reading Sample Test 2',
      topic: 'Reading comprehension',
      year: 2014,
      source: 'Agencia de Calidad de la Educación',
      url: 'https://s3.amazonaws.com/archivos.agenciaeducacion.cl/documentos-web/Ingl%C3%A9s/Simce_Reading_Sample_Test2.pdf',
    },
    {
      title: 'SIMCE Inglés 2014 - Listening Sample Test 1',
      topic: 'Listening comprehension',
      year: 2014,
      source: 'Agencia de Calidad de la Educación',
      url: 'https://s3.amazonaws.com/archivos.agenciaeducacion.cl/documentos-web/Ingl%C3%A9s/Simce_Listening_Sample_Test1.pdf',
    },
    {
      title: 'SIMCE Inglés 2014 - Manual del Profesor',
      topic: 'Guía de modelos de prueba (reading y listening)',
      year: 2014,
      source: 'Agencia de Calidad de la Educación',
      url: 'https://archivos.agenciaeducacion.cl/Manual_del_profesor_Ingles_Simce_2014_III_medio.pdf',
    },
    {
      title: 'B1 Preliminary for Schools: Sample Test',
      topic: 'Reading, writing, listening and speaking practice test',
      year: 2023,
      source: 'Cambridge Assessment English',
      url: 'https://www.cambridgeenglish.org/Images/577299-b1-preliminary-for-schools-computer-based-sample-tests.pdf',
    },
    {
      title: 'B1 Preliminary for Schools: Handbook for Teachers',
      topic: 'Exam format and skills overview (B1)',
      year: 2020,
      source: 'Cambridge Assessment English',
      url: 'https://www.cambridgeenglish.org/es/Images/168143-cambridge-english-preliminary-for-schools-teachers-handbook.pdf',
    },
    {
      title: 'B1 Preliminary Vocabulary List',
      topic: 'Vocabulary',
      year: 2025,
      source: 'Cambridge Assessment English',
      url: 'https://www.cambridgeenglish.org/Images/506887-b1-preliminary-vocabulary-list.pdf',
    },
    {
      title: "Writing B1: New Year's Resolutions",
      topic: 'Writing skills: personal goals and plans',
      year: 2019,
      source: 'British Council LearnEnglish',
      url: 'https://learnenglish.britishcouncil.org/sites/podcasts/files/LearnEnglish-Writing-B1-New-Years-resolution.pdf',
    },
    {
      title: 'Writing B1: Describing Charts',
      topic: 'Writing skills: describing graphs and data',
      year: 2020,
      source: 'British Council LearnEnglish',
      url: 'https://learnenglish.britishcouncil.org/sites/podcasts/files/LearnEnglish-Writing-B1-Describing-charts.pdf',
    },
    {
      title: 'Listening B1: Making a Decision',
      topic: 'Listening comprehension',
      year: 2019,
      source: 'British Council LearnEnglish',
      url: 'https://learnenglish.britishcouncil.org/sites/podcasts/files/LearnEnglish-Listening-B1-Making-a-decision.pdf',
    },
    {
      title: 'Reading B1: An Encyclopedia Entry',
      topic: 'Reading comprehension',
      year: 2019,
      source: 'British Council LearnEnglish',
      url: 'https://learnenglish.britishcouncil.org/sites/podcasts/files/LearnEnglish-Reading-B1-Encyclopedia-entry.pdf',
    },
    {
      title: 'Reading B2: The Buy Nothing Movement',
      topic: 'Reading comprehension (upper-intermediate)',
      year: 2019,
      source: 'British Council LearnEnglish',
      url: 'https://learnenglish.britishcouncil.org/sites/podcasts/files/LearnEnglish-Reading-B2-The-Buy-Nothing-movement.pdf',
    },
    {
      title: 'Writing B2: A CV',
      topic: 'Writing skills: vocational writing (CV)',
      year: 2019,
      source: 'British Council LearnEnglish',
      url: 'https://learnenglish.britishcouncil.org/sites/podcasts/files/LearnEnglish-Writing-B2-A-CV.pdf',
    },
    {
      title: 'Everyday Conversations: Learning American English',
      topic: 'Listening scripts and everyday dialogues',
      year: 2016,
      source: 'US Department of State - American English',
      url: 'https://americanenglish.state.gov/files/ae/resource_files/b_dialogues_everyday_conversations_english_lo_0.pdf',
    },
    {
      title: "Learner's Guide to American English Resources",
      topic: 'Índice de recursos gratuitos para aprender inglés',
      year: 2018,
      source: 'US Department of State - American English',
      url: 'https://americanspaces.state.gov/wp-content/uploads/sites/292/American-English-Materials-for-Learning.pdf',
    },
    {
      title: 'The Gift of the Magi (Graded Reader Text)',
      topic: 'Reading comprehension: short story',
      year: 2013,
      source: 'US Department of State - American English',
      url: 'https://americanenglish.state.gov/files/ae/resource_files/1-the_gift_of_the_magi_0.pdf',
    },
    {
      title: 'The Gift of the Magi: Student Learning Materials',
      topic: 'Reading comprehension and vocabulary workbook',
      year: 2013,
      source: 'US Department of State - American English',
      url: 'https://americanenglish.state.gov/files/ae/resource_files/gift_of_the_magi-instructions.pdf',
    },
    {
      title: 'The Gift of the Magi: Listening Transcript Correction',
      topic: 'Listening and dictation exercise',
      year: 2013,
      source: 'US Department of State - American English',
      url: 'https://americanenglish.state.gov/files/ae/resource_files/the_gift_of_the_magi_-_transcript_correction_worksheet.pdf',
    },
    {
      title: 'What Would You Do If...? Conditionals Activity',
      topic: 'Grammar: conditionals',
      year: 2015,
      source: 'US Department of State - American English',
      url: 'https://americanenglish.state.gov/files/ae/resource_files/conditionals_-_activity_3.pdf',
    },
  ],
}

export function getSeedPdfs(subjectKey) {
  const entries = SEED_LIBRARY[subjectKey] || []
  return entries.map((entry, i) => ({
    id: `seed-${subjectKey}-${slug(entry.title)}-${i}`,
    subject: subjectKey,
    title: entry.title,
    topic: entry.topic,
    uploader_name: entry.source,
    created_at: `${entry.year}-01-01T00:00:00.000Z`,
    url: entry.url,
    isSeed: true,
  }))
}
