export type Category = 'Ciencias' | 'Matemáticas' | 'Historia' | 'Literatura' | 'Tecnología' | 'Otros'

export interface CoverStyle {
  bg: string
  fg: string
  accent: string
  pattern: 'lines' | 'dots' | 'arcs' | 'grid' | 'waves'
}

/** Editorial metadata, written by hand in data/books.ts. */
export interface BookInfo {
  id: string
  title: string
  author: string
  category: Category
  subject: string
  description: string
  synopsis: string
  rating: number
  ratingsCount: number
  language: string
  /** Year of first publication (negative = BCE). */
  year: number
  /** Edition the digital text comes from. */
  edition: string
  popularity: number
  premium: boolean
  cover: CoverStyle
  tags: string[]
}

export interface ChapterMeta {
  title: string
  subtitle?: string
  part?: string
  chars: number
}

export interface AudioTrack {
  title: string
  file: string
  seconds: number
}

/** Facts about the real text and recording, generated by scripts/build-library.ts. */
export interface LibraryMeta {
  words: number
  bytes: number
  sourceUrl: string
  chapters: ChapterMeta[]
  audio?: { archiveId: string; mirrors: string[]; tracks: AudioTrack[] }
}

export interface Book extends BookInfo, LibraryMeta {
  pages: number
  hasAudio: boolean
  sizeMB: number
}

/** Content blocks: paragraph, heading or verse (line breaks preserved). */
export type Block = ['p' | 'h' | 'v', string]

export interface ChapterContent {
  title: string
  subtitle?: string
  part?: string
  blocks: Block[]
}

export interface BookContent {
  id: string
  chapters: ChapterContent[]
}

export type PlanId = 'free' | 'monthly' | 'annual'

export interface User {
  id: string
  firstName: string
  lastName: string
  email: string
  password: string
  role: string
  avatarColor: string
  avatarDataUrl?: string
  plan: PlanId
  createdAt: string
  provider: 'email' | 'google'
}

export type TaskStatus = 'pendiente' | 'en-progreso' | 'completada'
export type TaskPriority = 'alta' | 'media' | 'baja'

export interface Task {
  id: string
  title: string
  subject: string
  description: string
  dueDate: string // ISO date
  priority: TaskPriority
  progress: number
  status: TaskStatus
  bookId?: string
  /** Practice set that completes this task. */
  practiceSetId?: string
}

export interface Download {
  bookId: string
  downloadedAt: string
  bytes: number
}

export interface Bookmark {
  chapter: number
  /** Position within the chapter, 0..1 */
  position: number
  excerpt: string
  createdAt: string
}

export interface ReadingProgress {
  bookId: string
  chapter: number
  /** Position within the current chapter, 0..1 (layout independent). */
  position: number
  /** Whole-book progress, 0..100. */
  percent: number
  updatedAt: string
  bookmarks: Bookmark[]
}

export interface AudioProgress {
  bookId: string
  track: number
  position: number
  updatedAt: string
}

export interface Plan {
  id: PlanId
  name: string
  price: number
  period: 'mes' | 'año' | null
  description: string
  features: { label: string; included: boolean }[]
  recommended?: boolean
  /** Placeholder for a future Stripe Price ID. */
  stripePriceId?: string
}

export interface AppNotification {
  id: string
  title: string
  body: string
  createdAt: string
  read: boolean
  kind: 'download' | 'recommendation' | 'task' | 'system'
  link?: string
}

export type ThemeMode = 'light' | 'dark' | 'auto'

export interface Preferences {
  theme: ThemeMode
  language: 'es' | 'en'
  readerFontSize: number
  readerLineHeight: number
  readerFont: 'sans' | 'serif'
  /** null = follow the app theme */
  readerDark: boolean | null
  readerAnimations: boolean
  notifyTasks: boolean
  notifyRecommendations: boolean
  notifyDownloads: boolean
  shareActivity: boolean
  personalizedRecommendations: boolean
  audioVolume: number
  audioRate: number
}

/* ---------- Practice ---------- */

interface QuestionBase {
  id: string
  prompt: string
}

/** Auto-graded question types and the open (development) type. */
export type Question =
  | (QuestionBase & { kind: 'choice'; options: string[]; answer: number; explanation: string })
  | (QuestionBase & { kind: 'truefalse'; answer: boolean; explanation: string })
  | (QuestionBase & { kind: 'numeric'; answer: number; tolerance?: number; unit?: string; hint?: string; explanation: string })
  | (QuestionBase & { kind: 'short'; accepted: string[]; explanation: string })
  | (QuestionBase & { kind: 'order'; items: string[]; explanation: string })
  | (QuestionBase & {
      kind: 'open'
      guidance: string
      model?: string
      criteria?: string[]
      /** Show a drawing board (constructions, diagrams). */
      board?: boolean
      minWords?: number
    })

export type PracticeKind = 'ejercicios' | 'comprension' | 'analisis' | 'reflexion'

export interface PracticeSet {
  id: string
  bookId: string
  chapter: number
  title: string
  kind: PracticeKind
  description: string
  questions: Question[]
}

/** Answer stored per question: selected option, number, text, order, or self-assessment for open questions. */
export type AnswerValue = number | boolean | string | string[] | null

export interface PracticeResult {
  setId: string
  bookId: string
  chapter: number
  score: number
  max: number
  best: number
  attempts: number
  completedAt: string
}

export interface PracticeDraft {
  /** Written development for open questions. */
  text?: string
  /** Whiteboard drawing as a data URL. */
  drawing?: string
}
